<?php

header('Content-Type: application/json');

$naicsData = [

    ["code" => "1111", "name" => "Oilseed and Grain Farming"],
    ["code" => "1112", "name" => "Vegetable and Melon Farming"],
    ["code" => "1113", "name" => "Fruit and Tree Nut Farming"],
    ["code" => "1114", "name" => "Greenhouse, Nursery, and Floriculture Production"],
    ["code" => "1119", "name" => "Other Crop Farming"],
    ["code" => "1121", "name" => "Cattle Ranching and Farming"],
    ["code" => "1122", "name" => "Hog and Pig Farming"],
    ["code" => "1123", "name" => "Poultry and Egg Production"],
    ["code" => "1124", "name" => "Sheep and Goat Farming"],
    ["code" => "1125", "name" => "Aquaculture"],
    ["code" => "1129", "name" => "Other Animal Production"],
    ["code" => "1131", "name" => "Timber Tract Operations"],
    ["code" => "1132", "name" => "Forest Nurseries and Gathering of Forest Products"],
    ["code" => "1133", "name" => "Logging"],
    ["code" => "1141", "name" => "Fishing"],
    ["code" => "1142", "name" => "Hunting and Trapping"],
    ["code" => "1151", "name" => "Support Activities for Crop Production"],
    ["code" => "1152", "name" => "Support Activities for Animal Production"],
    ["code" => "1153", "name" => "Support Activities for Forestry"],
    ["code" => "2111", "name" => "Oil and Gas Extraction"],
    ["code" => "2121", "name" => "Coal Mining"],
    ["code" => "2122", "name" => "Metal Ore Mining"],
    ["code" => "2123", "name" => "Nonmetallic Mineral Mining and Quarrying"],
    ["code" => "2131", "name" => "Support Activities for Mining"],
    ["code" => "2211", "name" => "Electric Power Generation, Transmission and Distribution"],
    ["code" => "2212", "name" => "Natural Gas Distribution"],
    ["code" => "2213", "name" => "Water, Sewage and Other Systems"],
    ["code" => "2361", "name" => "Residential Building Construction"],
    ["code" => "2362", "name" => "Nonresidential Building Construction"],
    ["code" => "2371", "name" => "Utility System Construction"],
    ["code" => "2372", "name" => "Land Subdivision"],
    ["code" => "2373", "name" => "Highway, Street, and Bridge Construction"],
    ["code" => "2379", "name" => "Other Heavy and Civil Engineering Construction"],
    ["code" => "2381", "name" => "Foundation, Structure, and Building Exterior Contractors"],
    ["code" => "2382", "name" => "Building Equipment Contractors"],
    ["code" => "2383", "name" => "Building Finishing Contractors"],
    ["code" => "2389", "name" => "Other Specialty Trade Contractors"],
    ["code" => "3111", "name" => "Animal Food Manufacturing"],
    ["code" => "3112", "name" => "Grain and Oilseed Milling"],
    ["code" => "3113", "name" => "Sugar and Confectionery Product Manufacturing"],
    ["code" => "3114", "name" => "Fruit and Vegetable Preserving and Specialty Food Manufacturing"],
    ["code" => "3115", "name" => "Dairy Product Manufacturing"],
    ["code" => "3116", "name" => "Animal Slaughtering and Processing"],
    ["code" => "3117", "name" => "Seafood Product Preparation and Packaging"],
    ["code" => "3118", "name" => "Bakeries and Tortilla Manufacturing"],
    ["code" => "3119", "name" => "Other Food Manufacturing"],
    ["code" => "3121", "name" => "Beverage Manufacturing"],
    ["code" => "3122", "name" => "Tobacco Manufacturing"],
    ["code" => "3131", "name" => "Fiber, Yarn, and Thread Mills"],
    ["code" => "3132", "name" => "Fabric Mills"],
    ["code" => "3133", "name" => "Textile and Fabric Finishing and Fabric Coating Mills"],
    ["code" => "3141", "name" => "Textile Furnishings Mills"],
    ["code" => "3149", "name" => "Other Textile Product Mills"],
    ["code" => "3151", "name" => "Apparel Knitting Mills"],
    ["code" => "3152", "name" => "Cut and Sew Apparel Manufacturing"],
    ["code" => "3159", "name" => "Apparel Accessories and Other Apparel Manufacturing"],
    ["code" => "3161", "name" => "Leather and Hide Tanning and Finishing"],
    ["code" => "3162", "name" => "Footwear Manufacturing"],
    ["code" => "3169", "name" => "Other Leather and Allied Product Manufacturing"],
    ["code" => "3211", "name" => "Sawmills and Wood Preservation"],
    ["code" => "3212", "name" => "Veneer, Plywood, and Engineered Wood Product Manufacturing"],
    ["code" => "3219", "name" => "Other Wood Product Manufacturing"],
    ["code" => "3221", "name" => "Pulp, Paper, and Paperboard Mills"],
    ["code" => "3222", "name" => "Converted Paper Product Manufacturing"],
    ["code" => "3231", "name" => "Printing and Related Support Activities"],
    ["code" => "3241", "name" => "Petroleum and Coal Products Manufacturing"],
    ["code" => "3251", "name" => "Basic Chemical Manufacturing"],
    ["code" => "3252", "name" => "Resin, Synthetic Rubber, and Artificial Synthetic Fibers and Filaments Manufacturing"],
    ["code" => "3253", "name" => "Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing"],
    ["code" => "3254", "name" => "Pharmaceutical and Medicine Manufacturing"],
    ["code" => "3255", "name" => "Paint, Coating, and Adhesive Manufacturing"],
    ["code" => "3256", "name" => "Soap, Cleaning Compound, and Toilet Preparation Manufacturing"],
    ["code" => "3259", "name" => "Other Chemical Product and Preparation Manufacturing"],
    ["code" => "3261", "name" => "Plastics Product Manufacturing"],
    ["code" => "3262", "name" => "Rubber Product Manufacturing"],
    ["code" => "3271", "name" => "Clay Product and Refractory Manufacturing"],
    ["code" => "3272", "name" => "Glass and Glass Product Manufacturing"],
    ["code" => "3273", "name" => "Cement and Concrete Product Manufacturing"],
    ["code" => "3274", "name" => "Lime and Gypsum Product Manufacturing"],
    ["code" => "3279", "name" => "Other Nonmetallic Mineral Product Manufacturing"],
    ["code" => "3311", "name" => "Iron and Steel Mills and Ferroalloy Manufacturing"],
    ["code" => "3312", "name" => "Steel Product Manufacturing from Purchased Steel"],
    ["code" => "3313", "name" => "Alumina and Aluminum Production and Processing"],
    ["code" => "3314", "name" => "Nonferrous Metal (except Aluminum) Production and Processing"],
    ["code" => "3315", "name" => "Foundries"],
    ["code" => "3321", "name" => "Forging and Stamping"],
    ["code" => "3322", "name" => "Cutlery and Handtool Manufacturing"],
    ["code" => "3323", "name" => "Architectural and Structural Metals Manufacturing"],
    ["code" => "3324", "name" => "Boiler, Tank, and Shipping Container Manufacturing"],
    ["code" => "3325", "name" => "Hardware Manufacturing"],
    ["code" => "3326", "name" => "Spring and Wire Product Manufacturing"],
    ["code" => "3327", "name" => "Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing"],
    ["code" => "3328", "name" => "Coating, Engraving, Heat Treating, and Allied Activities"],
    ["code" => "3329", "name" => "Other Fabricated Metal Product Manufacturing"],
    ["code" => "3331", "name" => "Agriculture, Construction, and Mining Machinery Manufacturing"],
    ["code" => "3332", "name" => "Industrial Machinery Manufacturing"],
    ["code" => "3333", "name" => "Commercial and Service Industry Machinery Manufacturing"],
    ["code" => "3334", "name" => "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing"],
    ["code" => "3335", "name" => "Metalworking Machinery Manufacturing"],
    ["code" => "3336", "name" => "Engine, Turbine, and Power Transmission Equipment Manufacturing"],
    ["code" => "3339", "name" => "Other General Purpose Machinery Manufacturing"],
    ["code" => "3341", "name" => "Computer and Peripheral Equipment Manufacturing"],
    ["code" => "3342", "name" => "Communications Equipment Manufacturing"],
    ["code" => "3343", "name" => "Audio and Video Equipment Manufacturing"],
    ["code" => "3344", "name" => "Semiconductor and Other Electronic Component Manufacturing"],
    ["code" => "3345", "name" => "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing"],
    ["code" => "3346", "name" => "Manufacturing and Reproducing Magnetic and Optical Media"],
    ["code" => "3351", "name" => "Electric Lighting Equipment Manufacturing"],
    ["code" => "3352", "name" => "Household Appliance Manufacturing"],
    ["code" => "3353", "name" => "Electrical Equipment Manufacturing"],
    ["code" => "3359", "name" => "Other Electrical Equipment and Component Manufacturing"],
    ["code" => "3361", "name" => "Motor Vehicle Manufacturing"],
    ["code" => "3362", "name" => "Motor Vehicle Body and Trailer Manufacturing"],
    ["code" => "3363", "name" => "Motor Vehicle Parts Manufacturing"],
    ["code" => "3364", "name" => "Aerospace Product and Parts Manufacturing"],
    ["code" => "3365", "name" => "Railroad Rolling Stock Manufacturing"],
    ["code" => "3366", "name" => "Ship and Boat Building"],
    ["code" => "3369", "name" => "Other Transportation Equipment Manufacturing"],
    ["code" => "3371", "name" => "Household and Institutional Furniture and Kitchen Cabinet Manufacturing"],
    ["code" => "3372", "name" => "Office Furniture (including Fixtures) Manufacturing"],
    ["code" => "3379", "name" => "Other Furniture Related Product Manufacturing"],
    ["code" => "3391", "name" => "Medical Equipment and Supplies Manufacturing"],
    ["code" => "3399", "name" => "Other Miscellaneous Manufacturing"],
    ["code" => "4231", "name" => "Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers"],
    ["code" => "4232", "name" => "Furniture and Home Furnishing Merchant Wholesalers"],
    ["code" => "4233", "name" => "Lumber and Other Construction Materials Merchant Wholesalers"],
    ["code" => "4234", "name" => "Professional and Commercial Equipment and Supplies Merchant Wholesalers"],
    ["code" => "4235", "name" => "Metal and Mineral (except Petroleum) Merchant Wholesalers"],
    ["code" => "4236", "name" => "Electrical and Electronic Goods Merchant Wholesalers"],
    ["code" => "4237", "name" => "Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers"],
    ["code" => "4238", "name" => "Machinery, Equipment, and Supplies Merchant Wholesalers"],
    ["code" => "4239", "name" => "Miscellaneous Durable Goods Merchant Wholesalers"],
    ["code" => "4241", "name" => "Paper and Paper Product Merchant Wholesalers"],
    ["code" => "4242", "name" => "Drugs and Druggists' Sundries Merchant Wholesalers"],
    ["code" => "4243", "name" => "Apparel, Piece Goods, and Notions Merchant Wholesalers"],
    ["code" => "4244", "name" => "Grocery and Related Product Merchant Wholesalers"],
    ["code" => "4245", "name" => "Farm Product Raw Material Merchant Wholesalers"],
    ["code" => "4246", "name" => "Chemical and Allied Products Merchant Wholesalers"],
    ["code" => "4247", "name" => "Petroleum and Petroleum Products Merchant Wholesalers"],
    ["code" => "4248", "name" => "Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers"],
    ["code" => "4249", "name" => "Miscellaneous Nondurable Goods Merchant Wholesalers"],
    ["code" => "4251", "name" => "Wholesale Electronic Markets and Agents and Brokers"],
    ["code" => "4411", "name" => "Automobile Dealers"],
    ["code" => "4412", "name" => "Other Motor Vehicle Dealers"],
    ["code" => "4413", "name" => "Automotive Parts, Accessories, and Tire Stores"],
    ["code" => "4421", "name" => "Furniture Stores"],
    ["code" => "4422", "name" => "Home Furnishings Stores"],
    ["code" => "4431", "name" => "Electronics and Appliance Stores"],
    ["code" => "4441", "name" => "Building Material and Supplies Dealers"],
    ["code" => "4442", "name" => "Lawn and Garden Equipment and Supplies Stores"],
    ["code" => "4451", "name" => "Grocery Stores"],
    ["code" => "4452", "name" => "Specialty Food Stores"],
    ["code" => "4453", "name" => "Beer, Wine, and Liquor Stores"],
    ["code" => "4461", "name" => "Health and Personal Care Stores"],
    ["code" => "4471", "name" => "Gasoline Stations"],
    ["code" => "4481", "name" => "Clothing Stores"],
    ["code" => "4482", "name" => "Shoe Stores"],
    ["code" => "4483", "name" => "Jewelry, Luggage, and Leather Goods Stores"],
    ["code" => "4511", "name" => "Sporting Goods, Hobby, and Musical Instrument Stores"],
    ["code" => "4512", "name" => "Book Stores and News Dealers"],
    ["code" => "4521", "name" => "Department Stores"],
    ["code" => "4522", "name" => "Other General Merchandise Stores"],
    ["code" => "4531", "name" => "Florists"],
    ["code" => "4532", "name" => "Office Supplies, Stationery, and Gift Stores"],
    ["code" => "4533", "name" => "Used Merchandise Stores"],
    ["code" => "4539", "name" => "Other Miscellaneous Store Retailers"],
    ["code" => "4541", "name" => "Electronic Shopping and Mail-Order Houses"],
    ["code" => "4542", "name" => "Vending Machine Operators"],
    ["code" => "4543", "name" => "Direct Selling Establishments"],
    ["code" => "4811", "name" => "Scheduled Air Transportation"],
    ["code" => "4812", "name" => "Nonscheduled Air Transportation"],
    ["code" => "4821", "name" => "Rail Transportation"],
    ["code" => "4831", "name" => "Deep Sea, Coastal, and Great Lakes Water Transportation"],
    ["code" => "4832", "name" => "Inland Water Transportation"],
    ["code" => "4841", "name" => "General Freight Trucking"],
    ["code" => "4842", "name" => "Specialized Freight Trucking"],
    ["code" => "4851", "name" => "Urban Transit Systems"],
    ["code" => "4852", "name" => "Interurban and Rural Bus Transportation"],
    ["code" => "4853", "name" => "Taxi and Limousine Service"],
    ["code" => "4854", "name" => "School and Employee Bus Transportation"],
    ["code" => "4855", "name" => "Charter Bus Industry"],
    ["code" => "4859", "name" => "Other Transit and Ground Passenger Transportation"],
    ["code" => "4861", "name" => "Pipeline Transportation of Crude Oil"],
    ["code" => "4862", "name" => "Pipeline Transportation of Natural Gas"],
    ["code" => "4869", "name" => "Other Pipeline Transportation"],
    ["code" => "4871", "name" => "Scenic and Sightseeing Transportation, Land"],
    ["code" => "4872", "name" => "Scenic and Sightseeing Transportation, Water"],
    ["code" => "4879", "name" => "Scenic and Sightseeing Transportation, Other"],
    ["code" => "4881", "name" => "Support Activities for Air Transportation"],
    ["code" => "4882", "name" => "Support Activities for Rail Transportation"],
    ["code" => "4883", "name" => "Support Activities for Water Transportation"],
    ["code" => "4884", "name" => "Support Activities for Road Transportation"],
    ["code" => "4885", "name" => "Freight Transportation Arrangement"],
    ["code" => "4889", "name" => "Other Support Activities for Transportation"],
    ["code" => "4911", "name" => "Postal Service"],
    ["code" => "4921", "name" => "Couriers and Express Delivery Services"],
    ["code" => "4922", "name" => "Local Messengers and Local Delivery"],
    ["code" => "4931", "name" => "Warehousing and Storage"],
    ["code" => "5111", "name" => "Newspaper, Periodical, Book, and Directory Publishers"],
    ["code" => "5111", "name" => "Software Publishers"],
    ["code" => "5112", "name" => "Motion Picture and Video Industries"],
    ["code" => "5121", "name" => "Radio and Television Broadcasting"],
    ["code" => "5122", "name" => "Integrated Record Production/Distribution"],
    ["code" => "5122", "name" => "Other Sound Recording Industries"],
    ["code" => "5122", "name" => "Teleproduction and Other Postproduction Services"],
    ["code" => "5122", "name" => "Motion Picture and Video Distribution"],
    ["code" => "5122", "name" => "Teleproduction and Other Postproduction Services"],
    ["code" => "5122", "name" => "Theatrical Producers (Except Motion Picture)"],
    ["code" => "5122", "name" => "Motion Picture Theaters"],
    ["code" => "5122", "name" => "Other Motion Picture and Video Industries"],
    ["code" => "5122", "name" => "Teleproduction and Other Postproduction Services"],
    ["code" => "5122", "name" => "Sound Recording Studios"],
    ["code" => "5122", "name" => "Internet Publishing and Broadcasting"],
    ["code" => "5122", "name" => "Internet Service Providers"],
    ["code" => "5122", "name" => "Custom Computer Programming, Data Processing, Hosting, and Related Services"],
    ["code" => "5122", "name" => "Other Information Services"],
    ["code" => "5122", "name" => "Independent Artists, Writers, and Performers"],
    ["code" => "5122", "name" => "Libraries and Archives"],
    ["code" => "5122", "name" => "Other Information Services"],
    ["code" => "5122", "name" => "Other Information Services"],
    ["code" => "5122", "name" => "All Other Information Services"],
    ["code" => "5122", "name" => "Other Information Services"],
    ["code" => "5151", "name" => "Radio Broadcasting"],
    ["code" => "5151", "name" => "Radio Stations"],
    ["code" => "5151", "name" => "Television Broadcasting"],
    ["code" => "5151", "name" => "Cable and Other Subscription Programming"],
    ["code" => "5151", "name" => "Other Information Services"],
    ["code" => "5171", "name" => "Wired Telecommunications Carriers"],
    ["code" => "5171", "name" => "Wireless Telecommunications Carriers (except Satellite)"],
    ["code" => "5171", "name" => "Other Telecommunications"],
    ["code" => "5171", "name" => "Satellite Telecommunications"],
    ["code" => "5171", "name" => "All Other Telecommunications"],
    ["code" => "5182", "name" => "Data Processing, Hosting, and Related Services"],
    ["code" => "5191", "name" => "Other Information Services"],
    ["code" => "5211", "name" => "Monetary Authorities-Central Bank"],
    ["code" => "5221", "name" => "Depository Credit Intermediation"],
    ["code" => "5222", "name" => "Nondepository Credit Intermediation"],
    ["code" => "5223", "name" => "Activities Related to Credit Intermediation"],
    ["code" => "5231", "name" => "Securities and Commodity Contracts Intermediation and Brokerage"],
    ["code" => "5232", "name" => "Securities and Commodity Exchanges"],
    ["code" => "5239", "name" => "Other Financial Investment Activities"],
    ["code" => "5241", "name" => "Insurance Carriers"],
    ["code" => "5242", "name" => "Insurance Agencies and Brokerages"],
    ["code" => "5243", "name" => "Reinsurance Carriers"],
    ["code" => "5244", "name" => "Direct Life, Health, and Medical Insurance Carriers"],
    ["code" => "5245", "name" => "Other Direct Insurance (except Life, Health, and Medical) Carriers"],
    ["code" => "5246", "name" => "Insurance and Employee Benefit Funds"],
    ["code" => "5251", "name" => "Insurance and Employee Benefit Funds"],
    ["code" => "5259", "name" => "Other Investment Pools and Funds"],
    ["code" => "5311", "name" => "Lessors of Real Estate"],
    ["code" => "5312", "name" => "Offices of Real Estate Agents and Brokers"],
    ["code" => "5313", "name" => "Activities Related to Real Estate"],
    ["code" => "5321", "name" => "Automotive Equipment Rental and Leasing"],
    ["code" => "5322", "name" => "Consumer Goods Rental"],
    ["code" => "5323", "name" => "General Rental Centers"],
    ["code" => "5324", "name" => "Commercial and Industrial Machinery and Equipment Rental and Leasing"],
    ["code" => "5331", "name" => "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)"],
    ["code" => "5411", "name" => "Legal Services"],
    ["code" => "5412", "name" => "Accounting, Tax Preparation, Bookkeeping, and Payroll Services"],
    ["code" => "5413", "name" => "Architectural, Engineering, and Related Services"],
    ["code" => "5414", "name" => "Specialized Design Services"],
    ["code" => "5415", "name" => "Computer Systems Design and Related Services"],
    ["code" => "5416", "name" => "Management, Scientific, and Technical Consulting Services"],
    ["code" => "5417", "name" => "Scientific Research and Development Services"],
    ["code" => "5418", "name" => "Advertising, Public Relations, and Related Services"],
    ["code" => "5419", "name" => "Other Professional, Scientific, and Technical Services"],
    ["code" => "5511", "name" => "Management of Companies and Enterprises"],
    ["code" => "5611", "name" => "Office Administrative Services"],
    ["code" => "5612", "name" => "Facilities Support Services"],
    ["code" => "5613", "name" => "Employment Services"],
    ["code" => "5614", "name" => "Business Support Services"],
    ["code" => "5615", "name" => "Travel Arrangement and Reservation Services"],
    ["code" => "5616", "name" => "Investigation and Security Services"],
    ["code" => "5617", "name" => "Services to Buildings and Dwellings"],
    ["code" => "5619", "name" => "Other Support Services"],
    ["code" => "5621", "name" => "Waste Collection"],
    ["code" => "5622", "name" => "Waste Treatment and Disposal"],
    ["code" => "5629", "name" => "Remediation and Other Waste Management Services"],
    ["code" => "6111", "name" => "Elementary and Secondary Schools"],
    ["code" => "6112", "name" => "Junior Colleges"],
    ["code" => "6113", "name" => "Colleges, Universities, and Professional Schools"],
    ["code" => "6114", "name" => "Business Schools and Computer and Management Training"],
    ["code" => "6115", "name" => "Technical and Trade Schools"],
    ["code" => "6116", "name" => "Other Schools and Instruction"],
    ["code" => "6117", "name" => "Educational Support Services"],
    ["code" => "6211", "name" => "Offices of Physicians"],
    ["code" => "6212", "name" => "Offices of Dentists"],
    ["code" => "6213", "name" => "Offices of Other Health Practitioners"],
    ["code" => "6214", "name" => "Outpatient Care Centers"],
    ["code" => "6215", "name" => "Medical and Diagnostic Laboratories"],
    ["code" => "6216", "name" => "Home Health Care Services"],
    ["code" => "6219", "name" => "Other Ambulatory Health Care Services"],
    ["code" => "6221", "name" => "General Medical and Surgical Hospitals"],
    ["code" => "6222", "name" => "Psychiatric and Substance Abuse Hospitals"],
    ["code" => "6223", "name" => "Specialty (except Psychiatric and Substance Abuse) Hospitals"],
    ["code" => "6231", "name" => "Nursing Care Facilities (Skilled Nursing Facilities)"],
    ["code" => "6232", "name" => "Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities"],
    ["code" => "6233", "name" => "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly"],
    ["code" => "6239", "name" => "Other Residential Care Facilities"],
    ["code" => "6241", "name" => "Individual and Family Services"],
    ["code" => "6242", "name" => "Community Food and Housing, and Emergency and Other Relief Services"],
    ["code" => "6243", "name" => "Vocational Rehabilitation Services"],
    ["code" => "6244", "name" => "Child Day Care Services"],
    ["code" => "7111", "name" => "Performing Arts Companies"],
    ["code" => "7112", "name" => "Spectator Sports"],
    ["code" => "7113", "name" => "Promoters of Performing Arts, Sports, and Similar Events"],
    ["code" => "7114", "name" => "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures"],
    ["code" => "7115", "name" => "Independent Artists, Writers, and Performers"],
    ["code" => "7121", "name" => "Museums, Historical Sites, and Similar Institutions"],
    ["code" => "7131", "name" => "Amusement Parks and Arcades"],
    ["code" => "7132", "name" => "Gambling Industries"],
    ["code" => "7139", "name" => "Other Amusement and Recreation Industries"],
    ["code" => "7211", "name" => "Traveler Accommodation"],
    ["code" => "7212", "name" => "RV (Recreational Vehicle) Parks and Recreational Camps"],
    ["code" => "7213", "name" => "Rooming and Boarding Houses"],
    ["code" => "7223", "name" => "Special Food Services"],
    ["code" => "7224", "name" => "Drinking Places (Alcoholic Beverages)"],
    ["code" => "7225", "name" => "Restaurants and Other Eating Places"],
    ["code" => "8111", "name" => "Automotive Repair and Maintenance"],
    ["code" => "8112", "name" => "Electronic and Precision Equipment Repair and Maintenance"],
    ["code" => "8113", "name" => "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance"],
    ["code" => "8114", "name" => "Personal and Household Goods Repair and Maintenance"],
    ["code" => "8121", "name" => "Personal Care Services"],
    ["code" => "8122", "name" => "Death Care Services"],
    ["code" => "8123", "name" => "Drycleaning and Laundry Services"],
    ["code" => "8129", "name" => "Other Personal Services"],
    ["code" => "8131", "name" => "Religious Organizations"],
    ["code" => "8132", "name" => "Grantmaking and Giving Services"],
    ["code" => "8133", "name" => "Social Advocacy Organizations"],
    ["code" => "8134", "name" => "Civic and Social Organizations"],
    ["code" => "8139", "name" => "Business, Professional, Labor, Political, and Similar Organizations"],
    ["code" => "8141", "name" => "Private Households"],
    ["code" => "9211", "name" => "Executive, Legislative, and Other General Government Support"],
    ["code" => "9221", "name" => "Justice, Public Order, and Safety Activities"],
    ["code" => "9231", "name" => "Administration of Human Resource Programs"],
    ["code" => "9241", "name" => "Administration of Environmental Quality Programs"],
    ["code" => "9251", "name" => "Administration of Housing Programs, Urban Planning, and Community Development"],
    ["code" => "9261", "name" => "Administration of Economic Programs"],
    ["code" => "9271", "name" => "Space Research and Technology"],
    ["code" => "9281", "name" => "National Security and International Affairs"]

];

$term = isset($_GET['term']) ? $_GET['term'] : '';

$filteredData = array_filter($naicsData, function($industry) use ($term) {

    return stripos($industry['name'], $term) !== false;

});

echo json_encode(array_values($filteredData));

?>